// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum AmmoFlags_t : uint {
    AMMO_FORCE_DROP_IF_CARRIED = 1,
    AMMO_FLAG_MAX = 2,
    AMMO_RESERVE_STAYS_WITH_WEAPON = 2,
}
