// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum AnimScriptType : ushort {
    ANIMSCRIPT_TYPE_INVALID = ushort.MaxValue,
    ANIMSCRIPT_FUSE_GENERAL = 0,
    ANIMSCRIPT_FUSE_STATEMACHINE = 1,
}
