// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum BeamClipStyle_t : uint {
    kNOCLIP = 0,
    kGEOCLIP = 1,
    kBEAMCLIPSTYLE_NUMBITS = 2,
    kMODELCLIP = 2,
}
