// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum ChoreoLookAtMode_t : uint {
    eInvalid = uint.MaxValue,
    eChest = 0,
    eHead = 1,
    eEyesOnly = 2,
}
