// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum ChoreoLookAtSpeed_t : uint {
    eInvalid = uint.MaxValue,
    eSlow = 0,
    eMedium = 1,
    eFast = 2,
}
