// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum CNmCurrentSyncEventNode__InfoType_t : byte {
    IndexAndPercentage = 0,
    IndexOnly = 1,
    PercentageOnly = 2,
}
