// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum CNmSyncEventIndexConditionNode__TriggerMode_t : byte {
    ExactlyAtEventIndex = 0,
    GreaterThanEqualToEventIndex = 1,
}
