// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum DecalMode_t : byte {
    kDecalBlood = 0,
    kDecalDefault = 0,
    kDecalCloak = 1,
    kDecalCloakDamage = 2,
    kDecalMax = 3,
    kDecalInvalid = 255,
}
