// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum DecalFlags_t : uint {
    eNone = 0,
    eCannotClear = 1,
    eAllButCannotClear = 4294967294,
    eAll = 4294967295,
}
