// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum DestructiblePartDestructionDeathBehavior_t : uint {
    eDoNotKill = 0,
    eKill = 1,
    eGib = 2,
    eRemove = 3,
}
