// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum Disposition_t : uint {
    D_ER = 0,
    D_ERROR = 0,
    D_HATE = 1,
    D_HT = 1,
    D_FEAR = 2,
    D_FR = 2,
    D_LI = 3,
    D_LIKE = 3,
    D_NEUTRAL = 4,
    D_NU = 4,
}
