// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum EDestructiblePartRadiusDamageApplyType : uint {
    ScaleByExplosionRadius = 0,
    PrioritizeClosestPart = 1,
}
