// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum EDestructibleParts_DestroyParameterFlags : uint {
    None = 0,
    GenerateBreakpieces = 1,
    EnableFlinches = 2,
    Default = 3,
    ForceDamageApply = 4,
    IgnoreKillEntityFlag = 8,
    IgnoreHealthCheck = 16,
}
