// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum HandshakeTagType_t : uint {
    eInvalid = uint.MaxValue,
    eTask = 0,
    eMovement = 1,
    eCount = 2,
}
