// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum IKTargetCoordinateSystem : uint {
    IKTARGETCOORDINATESYSTEM_WorldSpace = 0,
    IKTARGETCOORDINATESYSTEM_ModelSpace = 1,
    IKTARGETCOORDINATESYSTEM_COUNT = 2,
}
