// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum NavScope_t : byte {
    eFirst = 0,
    eGround = 0,
    eAir = 1,
    eCount = 2,
    eInvalid = 255,
}
