// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum NmFootPhaseCondition_t : byte {
    LeftFootDown = 0,
    LeftFootPassing = 1,
    RightFootDown = 2,
    RightFootPassing = 3,
    LeftPhase = 4,
    RightPhase = 5,
}
