// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum NmFollowBoneMode_t : byte {
    RotationAndTranslation = 0,
    RotationOnly = 1,
    TranslationOnly = 2,
}
