// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum NmTransitionRule_t : byte {
    AllowTransition = 0,
    ConditionallyAllowTransition = 1,
    BlockTransition = 2,
}
