// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum OutOfPVSUpdates_t : uint {
    OOPVSUpdates_OptOut = 0,
    OOPVSUpdates_OptIn = 1,
    OOPVSUpdates_Default = 2,
    OOPVSUpdates_Count = 3,
}
