// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum ParticleSequenceCropOverride_t : uint {
    PARTICLE_SEQUENCE_CROP_OVERRIDE_DEFAULT = uint.MaxValue,
    PARTICLE_SEQUENCE_CROP_OVERRIDE_FORCE_OFF = 0,
    PARTICLE_SEQUENCE_CROP_OVERRIDE_FORCE_ON = 1,
}
