// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum PropDoorRotatingSpawnPos_t : uint {
    DOOR_SPAWN_CLOSED = 0,
    DOOR_SPAWN_OPEN_FORWARD = 1,
    DOOR_SPAWN_OPEN_BACK = 2,
    DOOR_SPAWN_AJAR = 3,
}
