// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum PulseDomainValueType_t : uint {
    INVALID = uint.MaxValue,
    ENTITY_NAME = 0,
    PANEL_ID = 1,
    COUNT = 2,
}
