// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum PulseBestOutflowRules_t : uint {
    SORT_BY_NUMBER_OF_VALID_CRITERIA = 0,
    SORT_BY_OUTFLOW_INDEX = 1,
}
