// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum RenderMeshSlotType_t : byte {
    RENDERMESH_SLOT_INVALID = byte.MaxValue,
    RENDERMESH_SLOT_PER_VERTEX = 0,
    RENDERMESH_SLOT_PER_INSTANCE = 1,
}
