// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum ScriptedMoveTo_t : uint {
    eWait = 0,
    eObsoleteBackCompat1 = 1,
    eObsoleteBackCompat2 = 2,
    eMoveWithGait = 3,
    eTeleport = 4,
    eWaitFacing = 5,
}
