// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum ScriptedHeldWeaponBehavior_t : uint {
    eInvalid = uint.MaxValue,
    eHolster = 0,
    eDeploy = 1,
    eDrop = 2,
}
