// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum SimpleConstraintSoundProfile__SimpleConstraintsSoundProfileKeypoints_t : uint {
    kMIN_THRESHOLD = 0,
    kMIN_FULL = 1,
    kHIGHWATER = 2,
}
