// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum SosActionLimitSortType_t : uint {
    SOS_LIMIT_SORTTYPE_HIGHEST = 0,
    SOS_LIMIT_SORTTYPE_LOWEST = 1,
}
