// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum TOGGLE_STATE : uint {
    DOOR_OPEN = 0,
    TS_AT_TOP = 0,
    DOOR_CLOSED = 1,
    TS_AT_BOTTOM = 1,
    DOOR_OPENING = 2,
    TS_GOING_UP = 2,
    DOOR_CLOSING = 3,
    TS_GOING_DOWN = 3,
}
