// <auto-generated />

using ServerGui.Schemas;

namespace ServerGui.Schemas.Enums;

public enum WeaponAttackType_t : uint {
    eInvalid = uint.MaxValue,
    ePrimary = 0,
    eSecondary = 1,
    eCount = 2,
}
